{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dosm-insights.fullname" . }}-config
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
{{- end }}
