apiVersion: v1
kind: Service
metadata:
  name: {{ include "dosm-insights.fullname" . }}
  annotations:
    {{- if .Values.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.prometheus.port }}"
    prometheus.io/path: "{{ .Values.prometheus.path }}"
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "dosm-insights.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
