apiVersion: v1
kind: Service
metadata:
  name: {{ include "dosm-insights.fullname" . }}
  annotations:
    {{- if .Values.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.prometheus.port }}"
    prometheus.io/path: "{{ .Values.prometheus.path }}"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "dosm-insights.name" . }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
