apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dosm-insights-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4m"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: dosm.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dosm-insights-svc
                port:
                  number: 80
