apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dosm-insights-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4m"
spec:
  ingressClassName: nginx
  rules:
    - host: dosm.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dosm-insights-svc
                port:
                  number: 80
