apiVersion: v1
kind: Service
metadata:
  name: dosm-insights-svc
spec:
  type: ClusterIP
  selector:
    app: dosm-insights-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
