apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: faq-chatbot-metrics
  namespace: dosm-prod
  labels:
    app: faq-chatbot-dosm-insights
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: faq-chatbot-dosm-insights
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
